//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertest.modelx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int idUser { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        public virtual Genders Genders { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
